/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.askthedude.run;

import io.vertx.core.Vertx;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class Main {
    private static final Logger LOGGER = LogManager.getLogger(Main.class);
    private void run(){
        var vertx = Vertx.vertx();
        var deployerFuture = vertx.deployVerticle(new VerticleRunner());
        deployerFuture.onComplete(e->{
            if(e.succeeded()){
                LOGGER.info("Initialized and started API application.");
            }else{
                LOGGER.warn("Couldn't start API application, {}", e.cause().toString());
            }
        });
    }

    public static void main(String[] args) {
        new Main().run();
    }
}
